/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package FrameView;

/**
 *
 * @author GloomySunday
 */
public class MainFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainFrame
     */
    private String maNV;
    public MainFrame() {
        initComponents();
    }

    MainFrame(String tentaikhoan) {
        maNV = tentaikhoan;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        xemThongTinCaNhan2 = new FrameView.XemThongTinCaNhan(maNV);
        xemDanhSachNV2 = new FrameView.XemDanhSachNV();
        xemDanhSachKH2 = new FrameView.XemDanhSachKH();
        xemDanhSachBDS1 = new FrameView.XemDanhSachBDS();
        xemDanhSachGiaoDich1 = new FrameView.XemDanhSachGiaoDich();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Quản Lý");

        jTabbedPane1.addTab("Cá nhân", xemThongTinCaNhan2);
        jTabbedPane1.addTab("Nhân viên", xemDanhSachNV2);
        jTabbedPane1.addTab("Khách hàng", xemDanhSachKH2);
        jTabbedPane1.addTab("Bất động sản", xemDanhSachBDS1);

        javax.swing.GroupLayout xemDanhSachGiaoDich1Layout = new javax.swing.GroupLayout(xemDanhSachGiaoDich1);
        xemDanhSachGiaoDich1.setLayout(xemDanhSachGiaoDich1Layout);
        xemDanhSachGiaoDich1Layout.setHorizontalGroup(
            xemDanhSachGiaoDich1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 795, Short.MAX_VALUE)
        );
        xemDanhSachGiaoDich1Layout.setVerticalGroup(
            xemDanhSachGiaoDich1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 601, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Giao dịch", xemDanhSachGiaoDich1);

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        jTabbedPane1.getAccessibleContext().setAccessibleName("jTabbedPane");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private FrameView.XemDanhSachBDS xemDanhSachBDS1;
    private FrameView.XemDanhSachGiaoDich xemDanhSachGiaoDich1;
    private FrameView.XemDanhSachKH xemDanhSachKH2;
    private FrameView.XemDanhSachNV xemDanhSachNV2;
    private FrameView.XemThongTinCaNhan xemThongTinCaNhan2;
    // End of variables declaration//GEN-END:variables
}
