/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package FrameView;

/**
 *
 * @author Agile
 */
public class ThemKhachHang extends javax.swing.JFrame {

    /**
     * Creates new form ThemKhachHang
     */
    public ThemKhachHang() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        lbTenKhachHang = new javax.swing.JLabel();
        tfTenKhachHang = new javax.swing.JTextField();
        lbLoaiKH = new javax.swing.JLabel();
        rbKhachHangMua = new javax.swing.JRadioButton();
        rbKhachHangBan = new javax.swing.JRadioButton();
        lbNgaySinh = new javax.swing.JLabel();
        lbGioiTinh = new javax.swing.JLabel();
        lbSoDienThoai = new javax.swing.JLabel();
        lbEmail = new javax.swing.JLabel();
        lbSoCMND = new javax.swing.JLabel();
        tfSoDienThoai = new javax.swing.JTextField();
        tfEmail = new javax.swing.JTextField();
        tfSoCMND = new javax.swing.JTextField();
        btHuy = new javax.swing.JButton();
        btHoanTat = new javax.swing.JButton();
        rbGioiTinhNam = new javax.swing.JRadioButton();
        rbGioiTinhNu = new javax.swing.JRadioButton();
        dcNgaySinh = new com.toedter.calendar.JDateChooser();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(470, 480));

        lbTenKhachHang.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        lbTenKhachHang.setText("Tên khách hàng");

        tfTenKhachHang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfTenKhachHangActionPerformed(evt);
            }
        });

        lbLoaiKH.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        lbLoaiKH.setText("Loại KH");

        buttonGroup1.add(rbKhachHangMua);
        rbKhachHangMua.setText("Mua");
        rbKhachHangMua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbKhachHangMuaActionPerformed(evt);
            }
        });

        buttonGroup1.add(rbKhachHangBan);
        rbKhachHangBan.setText("Bán");

        lbNgaySinh.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        lbNgaySinh.setText("Ngày Sinh");

        lbGioiTinh.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        lbGioiTinh.setText("Giới Tính");

        lbSoDienThoai.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        lbSoDienThoai.setText("Số điện thoại");

        lbEmail.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        lbEmail.setText("Email");

        lbSoCMND.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        lbSoCMND.setText("Số CMND");

        tfSoDienThoai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfSoDienThoaiActionPerformed(evt);
            }
        });

        tfEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfEmailActionPerformed(evt);
            }
        });

        tfSoCMND.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfSoCMNDActionPerformed(evt);
            }
        });

        btHuy.setText("Hủy");
        btHuy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btHuyActionPerformed(evt);
            }
        });

        btHoanTat.setText("Hoàn tất");

        buttonGroup2.add(rbGioiTinhNam);
        rbGioiTinhNam.setText("Nam");
        rbGioiTinhNam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbGioiTinhNamActionPerformed(evt);
            }
        });

        buttonGroup2.add(rbGioiTinhNu);
        rbGioiTinhNu.setText("Nữ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lbLoaiKH)
                    .addComponent(lbTenKhachHang)
                    .addComponent(lbNgaySinh)
                    .addComponent(lbGioiTinh)
                    .addComponent(lbSoDienThoai)
                    .addComponent(lbEmail)
                    .addComponent(lbSoCMND))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(tfSoCMND, javax.swing.GroupLayout.DEFAULT_SIZE, 220, Short.MAX_VALUE)
                    .addComponent(tfTenKhachHang, javax.swing.GroupLayout.DEFAULT_SIZE, 220, Short.MAX_VALUE)
                    .addComponent(tfEmail, javax.swing.GroupLayout.DEFAULT_SIZE, 220, Short.MAX_VALUE)
                    .addComponent(tfSoDienThoai, javax.swing.GroupLayout.DEFAULT_SIZE, 220, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(rbKhachHangMua)
                        .addGap(4, 4, 4)
                        .addComponent(rbKhachHangBan))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(rbGioiTinhNam)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(rbGioiTinhNu))
                    .addComponent(dcNgaySinh, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(96, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btHuy)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btHoanTat)
                .addGap(45, 45, 45))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbTenKhachHang, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfTenKhachHang, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbKhachHangMua)
                    .addComponent(rbKhachHangBan)
                    .addComponent(lbLoaiKH, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lbNgaySinh, javax.swing.GroupLayout.DEFAULT_SIZE, 26, Short.MAX_VALUE)
                    .addComponent(dcNgaySinh, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbGioiTinh, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rbGioiTinhNam)
                    .addComponent(rbGioiTinhNu))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbSoDienThoai, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfSoDienThoai, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfSoCMND, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbSoCMND, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btHuy, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btHoanTat, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(47, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tfTenKhachHangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfTenKhachHangActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfTenKhachHangActionPerformed

    private void rbKhachHangMuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbKhachHangMuaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbKhachHangMuaActionPerformed

    private void tfSoDienThoaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfSoDienThoaiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfSoDienThoaiActionPerformed

    private void tfEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfEmailActionPerformed

    private void tfSoCMNDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfSoCMNDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfSoCMNDActionPerformed

    private void btHuyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btHuyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btHuyActionPerformed

    private void rbGioiTinhNamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbGioiTinhNamActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbGioiTinhNamActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ThemKhachHang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ThemKhachHang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ThemKhachHang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ThemKhachHang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ThemKhachHang().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btHoanTat;
    private javax.swing.JButton btHuy;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private com.toedter.calendar.JDateChooser dcNgaySinh;
    private javax.swing.JLabel lbEmail;
    private javax.swing.JLabel lbGioiTinh;
    private javax.swing.JLabel lbLoaiKH;
    private javax.swing.JLabel lbNgaySinh;
    private javax.swing.JLabel lbSoCMND;
    private javax.swing.JLabel lbSoDienThoai;
    private javax.swing.JLabel lbTenKhachHang;
    private javax.swing.JRadioButton rbGioiTinhNam;
    private javax.swing.JRadioButton rbGioiTinhNu;
    private javax.swing.JRadioButton rbKhachHangBan;
    private javax.swing.JRadioButton rbKhachHangMua;
    private javax.swing.JTextField tfEmail;
    private javax.swing.JTextField tfSoCMND;
    private javax.swing.JTextField tfSoDienThoai;
    private javax.swing.JTextField tfTenKhachHang;
    // End of variables declaration//GEN-END:variables
}
